### ISSUE TITLE
license

### ISSUE THREAD

**Issue by caoHenriques** [jm-shi/Snake#2]
Hi,

I would like to use your code for a personal opensource research project.
What is the licence?

by the way, congratulations your code is very organized :)

thanks

**Comment by caoHenriques** [comment]
naturally, I intend to give you the diserved credits for the original code

**Comment by jm-shi** [comment]
Hey, @caoHenriques, I apologize for getting back to you so late. I don't regularly check this repo and only just saw your message. I've added an MIT license. If you're still interested, feel free to make as much modifications to the code as you want.
